//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkManagermentWeb.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkManagermentWeb.Domain.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account already exist.
        /// </summary>
        public static string Account_already_exist {
            get {
                return ResourceManager.GetString("Account already exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        public static string Account_Details {
            get {
                return ResourceManager.GetString("Account Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account updated successfully.
        /// </summary>
        public static string Account_updated_successfully {
            get {
                return ResourceManager.GetString("Account updated successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountType.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Member.
        /// </summary>
        public static string Add_Member {
            get {
                return ResourceManager.GetString("Add Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Project.
        /// </summary>
        public static string Add_Project {
            get {
                return ResourceManager.GetString("Add Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Subtask.
        /// </summary>
        public static string Add_Subtask {
            get {
                return ResourceManager.GetString("Add Subtask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added by.
        /// </summary>
        public static string Added_by {
            get {
                return ResourceManager.GetString("Added by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? Log in.
        /// </summary>
        public static string Already_have_an_account__Log_in {
            get {
                return ResourceManager.GetString("Already have an account? Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure with this action?.
        /// </summary>
        public static string Are_you_sure_with_this_action_ {
            get {
                return ResourceManager.GetString("Are you sure with this action?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee.
        /// </summary>
        public static string Assignee {
            get {
                return ResourceManager.GetString("Assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to login.
        /// </summary>
        public static string Back_to_login {
            get {
                return ResourceManager.GetString("Back to login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        public static string Bad_Request {
            get {
                return ResourceManager.GetString("Bad Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box search.
        /// </summary>
        public static string Box_search {
            get {
                return ResourceManager.GetString("Box search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug.
        /// </summary>
        public static string Bug {
            get {
                return ResourceManager.GetString("Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO.
        /// </summary>
        public static string CEO {
            get {
                return ResourceManager.GetString("CEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Profile.
        /// </summary>
        public static string Change_Profile {
            get {
                return ResourceManager.GetString("Change Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a new member.
        /// </summary>
        public static string Choose_a_new_member {
            get {
                return ResourceManager.GetString("Choose a new member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Category.
        /// </summary>
        public static string Choose_Category {
            get {
                return ResourceManager.GetString("Choose Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Priority.
        /// </summary>
        public static string Choose_Priority {
            get {
                return ResourceManager.GetString("Choose Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Project.
        /// </summary>
        public static string Choose_Project {
            get {
                return ResourceManager.GetString("Choose Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Role.
        /// </summary>
        public static string Choose_Role {
            get {
                return ResourceManager.GetString("Choose Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Status.
        /// </summary>
        public static string Choose_Status {
            get {
                return ResourceManager.GetString("Choose Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSED.
        /// </summary>
        public static string CLOSED {
            get {
                return ResourceManager.GetString("CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could.
        /// </summary>
        public static string Could {
            get {
                return ResourceManager.GetString("Could", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string Create_an_account {
            get {
                return ResourceManager.GetString("Create an account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create now!.
        /// </summary>
        public static string Create_now_ {
            get {
                return ResourceManager.GetString("Create now!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string Current_Password {
            get {
                return ResourceManager.GetString("Current Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactive.
        /// </summary>
        public static string Deactive {
            get {
                return ResourceManager.GetString("Deactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete it.
        /// </summary>
        public static string Delete_it {
            get {
                return ResourceManager.GetString("Delete it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove this task..
        /// </summary>
        public static string Do_you_really_want_to_remove_this_task_ {
            get {
                return ResourceManager.GetString("Do you really want to remove this task.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do It Now.
        /// </summary>
        public static string DoItNow {
            get {
                return ResourceManager.GetString("DoItNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string Edit_Profile {
            get {
                return ResourceManager.GetString("Edit Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project.
        /// </summary>
        public static string Edit_Project {
            get {
                return ResourceManager.GetString("Edit Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task.
        /// </summary>
        public static string Edit_Task {
            get {
                return ResourceManager.GetString("Edit Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Comfirmed.
        /// </summary>
        public static string Email_Comfirmed {
            get {
                return ResourceManager.GetString("Email Comfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Comfirmed Successfully!.
        /// </summary>
        public static string Email_Comfirmed_Successfully_ {
            get {
                return ResourceManager.GetString("Email Comfirmed Successfully!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sent Successfully!.
        /// </summary>
        public static string Email_Sent_Successfully_ {
            get {
                return ResourceManager.GetString("Email Sent Successfully!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string En {
            get {
                return ResourceManager.GetString("En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string End_Date {
            get {
                return ResourceManager.GetString("End Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered date.
        /// </summary>
        public static string Entered_date {
            get {
                return ResourceManager.GetString("Entered date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured.. please try again.
        /// </summary>
        public static string Error_occured___please_try_again {
            get {
                return ResourceManager.GetString("Error occured.. please try again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing....
        /// </summary>
        public static string Executing___ {
            get {
                return ResourceManager.GetString("Executing...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanse.
        /// </summary>
        public static string Expanse {
            get {
                return ResourceManager.GetString("Expanse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Account Connected.
        /// </summary>
        public static string ExternalAccountConnected {
            get {
                return ResourceManager.GetString("ExternalAccountConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        public static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter_Tasks {
            get {
                return ResourceManager.GetString("Filter Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string Forgot_password {
            get {
                return ResourceManager.GetString("Forgot password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Full_Name {
            get {
                return ResourceManager.GetString("Full Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gantt Chart.
        /// </summary>
        public static string Gantt_Chart {
            get {
                return ResourceManager.GetString("Gantt Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string h {
            get {
                return ResourceManager.GetString("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve.
        /// </summary>
        public static string Improve {
            get {
                return ResourceManager.GetString("Improve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inprogress.
        /// </summary>
        public static string Inprogress {
            get {
                return ResourceManager.GetString("Inprogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items per page.
        /// </summary>
        public static string ItemsPerPageText {
            get {
                return ResourceManager.GetString("ItemsPerPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated at.
        /// </summary>
        public static string Last_updated_at {
            get {
                return ResourceManager.GetString("Last updated at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading___ {
            get {
                return ResourceManager.GetString("Loading...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to continue.
        /// </summary>
        public static string Log_in_to_continue {
            get {
                return ResourceManager.GetString("Log in to continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login false, wrong credentials.
        /// </summary>
        public static string Login_false__wrong_credentials {
            get {
                return ResourceManager.GetString("Login false, wrong credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successfully.
        /// </summary>
        public static string Login_successfully {
            get {
                return ResourceManager.GetString("Login successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage account.
        /// </summary>
        public static string Manage_account {
            get {
                return ResourceManager.GetString("Manage account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark All As Read.
        /// </summary>
        public static string Mark_All_As_Read {
            get {
                return ResourceManager.GetString("Mark All As Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must.
        /// </summary>
        public static string Must {
            get {
                return ResourceManager.GetString("Must", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only this task creator have delete permission.
        /// </summary>
        public static string Must_be_this_task_creator_to_delete {
            get {
                return ResourceManager.GetString("Must be this task creator to delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account.
        /// </summary>
        public static string New_Account {
            get {
                return ResourceManager.GetString("New Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string New_Project {
            get {
                return ResourceManager.GetString("New Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Task.
        /// </summary>
        public static string New_Task {
            get {
                return ResourceManager.GetString("New Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string Not_Found {
            get {
                return ResourceManager.GetString("Not Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Verified.
        /// </summary>
        public static string Not_Verified {
            get {
                return ResourceManager.GetString("Not Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification not found.
        /// </summary>
        public static string Notification_not_found {
            get {
                return ResourceManager.GetString("Notification not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        public static string NotStarted {
            get {
                return ResourceManager.GetString("NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Sync.
        /// </summary>
        public static string NotSync {
            get {
                return ResourceManager.GetString("NotSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN.
        /// </summary>
        public static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openning Issuess.
        /// </summary>
        public static string Openning_Issuess {
            get {
                return ResourceManager.GetString("Openning Issuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openning Tasks.
        /// </summary>
        public static string Openning_Tasks {
            get {
                return ResourceManager.GetString("Openning Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or coutinue with:.
        /// </summary>
        public static string Or_coutinue_with_ {
            get {
                return ResourceManager.GetString("Or coutinue with:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} of {2} items.
        /// </summary>
        public static string PaginationItemsTextFormat {
            get {
                return ResourceManager.GetString("PaginationItemsTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Code.
        /// </summary>
        public static string Parent_Code {
            get {
                return ResourceManager.GetString("Parent Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent task not found.
        /// </summary>
        public static string Parent_task_not_found {
            get {
                return ResourceManager.GetString("Parent task not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Work Item.
        /// </summary>
        public static string Parent_Work_Item {
            get {
                return ResourceManager.GetString("Parent Work Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project add member successfully.
        /// </summary>
        public static string Project_add_member_successfully {
            get {
                return ResourceManager.GetString("Project add member successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project created successfully.
        /// </summary>
        public static string Project_created_successfully {
            get {
                return ResourceManager.GetString("Project created successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Details.
        /// </summary>
        public static string Project_Details {
            get {
                return ResourceManager.GetString("Project Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Lifetime.
        /// </summary>
        public static string Project_Lifetime {
            get {
                return ResourceManager.GetString("Project Lifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project List.
        /// </summary>
        public static string Project_List {
            get {
                return ResourceManager.GetString("Project List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not found.
        /// </summary>
        public static string Project_not_found {
            get {
                return ResourceManager.GetString("Project not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project remove member successfully.
        /// </summary>
        public static string Project_remove_member_successfully {
            get {
                return ResourceManager.GetString("Project remove member successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project updated successfully.
        /// </summary>
        public static string Project_updated_successfully {
            get {
                return ResourceManager.GetString("Project updated successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager.
        /// </summary>
        public static string ProjectManager {
            get {
                return ResourceManager.GetString("ProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string Read_More {
            get {
                return ResourceManager.GetString("Read More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Password.
        /// </summary>
        public static string Recover_Password {
            get {
                return ResourceManager.GetString("Recover Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor.
        /// </summary>
        public static string Refactor {
            get {
                return ResourceManager.GetString("Refactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration completed.
        /// </summary>
        public static string Registration_completed {
            get {
                return ResourceManager.GetString("Registration completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Member.
        /// </summary>
        public static string Remove_Member {
            get {
                return ResourceManager.GetString("Remove Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resset Filter.
        /// </summary>
        public static string Reset_Filter {
            get {
                return ResourceManager.GetString("Reset Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Save_Changes {
            get {
                return ResourceManager.GetString("Save Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Saving___ {
            get {
                return ResourceManager.GetString("Saving...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Verify Token.
        /// </summary>
        public static string Send_Verify_Token {
            get {
                return ResourceManager.GetString("Send Verify Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending....
        /// </summary>
        public static string Sending___ {
            get {
                return ResourceManager.GetString("Sending...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending verify code....
        /// </summary>
        public static string Sending_verify_code___ {
            get {
                return ResourceManager.GetString("Sending verify code...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should.
        /// </summary>
        public static string Should {
            get {
                return ResourceManager.GetString("Should", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Password.
        /// </summary>
        public static string Show_Password {
            get {
                return ResourceManager.GetString("Show Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-in with Microsoft.
        /// </summary>
        public static string Sign_in_with_Microsoft {
            get {
                return ResourceManager.GetString("Sign-in with Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up to continue.
        /// </summary>
        public static string Sign_up_to_continue {
            get {
                return ResourceManager.GetString("Sign up to continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignUp.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some thing went wrong..
        /// </summary>
        public static string Some_thing_went_wrong_ {
            get {
                return ResourceManager.GetString("Some thing went wrong.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address..
        /// </summary>
        public static string Sorry__there_s_nothing_at_this_address_ {
            get {
                return ResourceManager.GetString("Sorry, there\'s nothing at this address.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you need to login Microsoft to access this feature..
        /// </summary>
        public static string Sorry__you_need_to_login_Microsoft_to_access_this_feature_ {
            get {
                return ResourceManager.GetString("Sorry, you need to login Microsoft to access this feature.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start At.
        /// </summary>
        public static string Start_At {
            get {
                return ResourceManager.GetString("Start At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Start_Date {
            get {
                return ResourceManager.GetString("Start Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date - End Date.
        /// </summary>
        public static string Start_Date___End_Date {
            get {
                return ResourceManager.GetString("Start Date - End Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start your new plan or product development with new project.
        /// </summary>
        public static string Start_your_new_plan_or_product_development_with_new_project {
            get {
                return ResourceManager.GetString("Start your new plan or product development with new project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status code 400 - Bad Request.
        /// </summary>
        public static string Status_code_400___Bad_Request {
            get {
                return ResourceManager.GetString("Status code 400 - Bad Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status code 401 - Unauthorized.
        /// </summary>
        public static string Status_code_401___Unauthorized {
            get {
                return ResourceManager.GetString("Status code 401 - Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status code 403 - Forbidden.
        /// </summary>
        public static string Status_code_403___Forbidden {
            get {
                return ResourceManager.GetString("Status code 403 - Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status code 404.
        /// </summary>
        public static string Status_code_404 {
            get {
                return ResourceManager.GetString("Status code 404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub work items.
        /// </summary>
        public static string Sub_work_items {
            get {
                return ResourceManager.GetString("Sub work items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully sync.
        /// </summary>
        public static string Successfully_sync {
            get {
                return ResourceManager.GetString("Successfully sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully sync this task to Calendar.
        /// </summary>
        public static string Successfully_sync_this_task_to_Calendar {
            get {
                return ResourceManager.GetString("Successfully sync this task to Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Task To Calendar.
        /// </summary>
        public static string Sync_Task_To_Calendar {
            get {
                return ResourceManager.GetString("Sync Task To Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Calendar.
        /// </summary>
        public static string SyncCalendar {
            get {
                return ResourceManager.GetString("SyncCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synced.
        /// </summary>
        public static string Synced {
            get {
                return ResourceManager.GetString("Synced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task contain undone tasks.
        /// </summary>
        public static string Task_contain_undone_tasks {
            get {
                return ResourceManager.GetString("Task contain undone tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task created successfully.
        /// </summary>
        public static string Task_created_successfully {
            get {
                return ResourceManager.GetString("Task created successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Details.
        /// </summary>
        public static string Task_Details {
            get {
                return ResourceManager.GetString("Task Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Infomation.
        /// </summary>
        public static string Task_Infomation {
            get {
                return ResourceManager.GetString("Task Infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task must be resolved before change to done.
        /// </summary>
        public static string Task_must_be_resolved_before_change_to_done {
            get {
                return ResourceManager.GetString("Task must be resolved before change to done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task not found.
        /// </summary>
        public static string Task_not_found {
            get {
                return ResourceManager.GetString("Task not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task(s) to Calendar.
        /// </summary>
        public static string task_s__to_Calendar {
            get {
                return ResourceManager.GetString("task(s) to Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task saved successfully.
        /// </summary>
        public static string Task_saved_successfully {
            get {
                return ResourceManager.GetString("Task saved successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task was deleted.
        /// </summary>
        public static string Task_was_deleted {
            get {
                return ResourceManager.GetString("Task was deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks synced successfully..
        /// </summary>
        public static string Tasks_Synced_Successfully_ {
            get {
                return ResourceManager.GetString("Tasks Synced Successfully.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To do.
        /// </summary>
        public static string Todo {
            get {
                return ResourceManager.GetString("Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable input data.
        /// </summary>
        public static string Unavailable_input_data {
            get {
                return ResourceManager.GetString("Unavailable input data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Project.
        /// </summary>
        public static string Update_Project {
            get {
                return ResourceManager.GetString("Update Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Task.
        /// </summary>
        public static string Update_Task {
            get {
                return ResourceManager.GetString("Update Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string User_not_found {
            get {
                return ResourceManager.GetString("User not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already taken..
        /// </summary>
        public static string Username_already_taken_ {
            get {
                return ResourceManager.GetString("Username already taken.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phone Number.
        /// </summary>
        public static string Verify_Phone_Number {
            get {
                return ResourceManager.GetString("Verify Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifyng....
        /// </summary>
        public static string Verifyng___ {
            get {
                return ResourceManager.GetString("Verifyng...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string Vi {
            get {
                return ResourceManager.GetString("Vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent comfirm url to your email. Please go to your inbox..
        /// </summary>
        public static string We_sent_comfirm_url_to_your_email__Please_go_to_your_inbox_ {
            get {
                return ResourceManager.GetString("We sent comfirm url to your email. Please go to your inbox.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent to you recover password email. Please check inbox to countinue..
        /// </summary>
        public static string We_sent_to_you_recover_password_email__Please_check_inbox_to_countinue_ {
            get {
                return ResourceManager.GetString("We sent to you recover password email. Please check inbox to countinue.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won&apos;t.
        /// </summary>
        public static string Wont {
            get {
                return ResourceManager.GetString("Wont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace not found.
        /// </summary>
        public static string Workspace_not_found {
            get {
                return ResourceManager.GetString("Workspace not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong current password.
        /// </summary>
        public static string Wrong_current_password {
            get {
                return ResourceManager.GetString("Wrong current password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already use this request to change password before.
        /// </summary>
        public static string You_already_use_this_request_to_change_password_before {
            get {
                return ResourceManager.GetString("You already use this request to change password before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have permission to access this request..
        /// </summary>
        public static string You_dont_have_permission_to_access_this_request_ {
            get {
                return ResourceManager.GetString("You dont have permission to access this request.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to login to access this request..
        /// </summary>
        public static string You_need_to_login_to_access_this_request_ {
            get {
                return ResourceManager.GetString("You need to login to access this request.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email was confirmed succesfully!. Now you can manage task on our system..
        /// </summary>
        public static string Your_email_was_confirmed_succesfully___Now_you_can_manage_task_on_our_system_ {
            get {
                return ResourceManager.GetString("Your email was confirmed succesfully!. Now you can manage task on our system.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Otp.
        /// </summary>
        public static string Your_Otp {
            get {
                return ResourceManager.GetString("Your Otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your page you are looking for does not exist..
        /// </summary>
        public static string Your_page_you_are_looking_for_does_not_exist_ {
            get {
                return ResourceManager.GetString("Your page you are looking for does not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request is not valid. The server cannot process this request due to there is something wrong with your request..
        /// </summary>
        public static string Your_request_is_not_valid__The_server_cannot_process_this_request_due_to_there_is_something_wrong_with_your_request_ {
            get {
                return ResourceManager.GetString("Your request is not valid. The server cannot process this request due to there is" +
                        " something wrong with your request.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string Zoom_In {
            get {
                return ResourceManager.GetString("Zoom In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string Zoom_Out {
            get {
                return ResourceManager.GetString("Zoom Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Fit.
        /// </summary>
        public static string Zoom_to_Fit {
            get {
                return ResourceManager.GetString("Zoom to Fit", resourceCulture);
            }
        }
    }
}
